### ISSUE TITLE
PiwigoClientWsExt folder instead of PiwigoClientWsExts

### ISSUE THREAD

**Issue by fabienli** [extorn/PiwigoClientWsExts#2]
Hello,

when installing the plugin I got an error that class PiwigoClientWsExt_maintain could not be found.
This issue happens both via the direct download in piwigo's interface, or via the tarball available from plugin's page: https://piwigo.org/ext/extension_view.php?eid=880 

Solution I found to work this around was to rename the folder  PiwigoClientWsExt as PiwigoClientWsExts with a final s.

**Comment by extorn** [comment]
Sorry about this this should be fixed with all the latest releases.
Delete the old folder PiwigoClientWsExt from your plugins folder manually and reinstall the plugin. you don't lose any settings.

**Comment by extorn** [comment]
solved in later versions
