### ISSUE TITLE
Error when batch download

### ISSUE THREAD

**Issue by tmkklivecom** [extorn/PiwigoClientWsExts#3]
Fatal error: Uncaught ArgumentCountError: Too few arguments to function get_extended_desc_cliext(), 1 passed in /volume1/web/piwigo/include/functions_plugins.inc.php on line 214 and exactly 2 expected in /volume1/web/piwigo/plugins/PiwigoClientWsExts/include/pwg.extended_description.php:25 Stack trace: #0 /volume1/web/piwigo/include/functions_plugins.inc.php(214): get_extended_desc_cliext('') #1 /volume1/web/piwigo/plugins/BatchDownloader/include/BatchDownloader.class.php(801): trigger_change('render_category...', '') #2 /volume1/web/piwigo/plugins/BatchDownloader/include/BatchDownloader.class.php(952): BatchDownloader->getNames() #3 /volume1/web/piwigo/plugins/BatchDownloader/include/events.inc.php(230): BatchDownloader->getSetInfo() #4 /volume1/web/piwigo/include/functions_plugins.inc.php(264): batch_download_applymenu(Array) #5 /volume1/web/piwigo/include/block.class.php(181): trigger_notify('blockmanager_ap...', Array) #6 /volume1/web/piwigo/include/menubar.inc.php(370): BlockManager->apply('MENUBAR', 'menubar.tpl') # in /volume1/web/piwigo/plugins/PiwigoClientWsExts/include/pwg.extended_description.php on line 25

Workaround - PiwigoClientWsExts deactivation

**Comment by extorn** [comment]
this is solved in the latest version 1.0.17 Thanks for telling me! Using the stacktrace you provided allowed me to solve it 👍

**Comment by tmkklivecom** [comment]
👍
